<?php

defined('ABSPATH') or die( "Bye bye" );

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class CfUAO {
	private $cf7_uao_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'cf7_uao_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'cf7_uao_page_init' ) );
	}

   
            public function cf7_uao_add_plugin_page() {
                
                add_submenu_page( 
                    'wpcf7',
                    esc_html__( 'CF7 UAO - Marketing Cloud', 'cf7_UAO' ),
                    esc_html__( 'CF7 UAO', 'cf7_UAO' ),
                    'manage_options',
                    'cf7-uao',
                    array( $this, 'cf7_uao_create_admin_page' )
                );
            }
      
	public function cf7_uao_create_admin_page() {
		$this->cf7_uao_options = get_option( 'cf7_uao_option_name' ); ?>

		<div class="wrap">
			<h2>cf7_UAO</h2>
			<p>Bienvenido a la configuración de los patrones para identificar los formularios que van para marketing Cloud</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'cf7_uao_option_group' );
					do_settings_sections( 'cf7-uao-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function cf7_uao_page_init() {
		register_setting(
			'cf7_uao_option_group', // option_group
			'cf7_uao_option_name', // option_name
			array( $this, 'cf7_uao_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'cf7_uao_setting_section', // id
			'Nombres de formulario patrón para identificar los formularios', // title
			array( $this, 'cf7_uao_section_info' ), // callback
			'cf7-uao-admin' // page
		);

		add_settings_field(
			'nombre_formulario_de_programas_0', // id
			'Nombre formulario de programas', // title
			array( $this, 'nombre_formulario_de_programas_0_callback' ), // callback
			'cf7-uao-admin', // page
			'cf7_uao_setting_section' // section
		);

		add_settings_field(
			'nombre_formulario_de_eventos_1', // id
			'Nombre formulario de eventos', // title
			array( $this, 'nombre_formulario_de_eventos_1_callback' ), // callback
			'cf7-uao-admin', // page
			'cf7_uao_setting_section' // section
		);
	}

	public function cf7_uao_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['nombre_formulario_de_programas_0'] ) ) {
			$sanitary_values['nombre_formulario_de_programas_0'] = sanitize_text_field( $input['nombre_formulario_de_programas_0'] );
		}

		if ( isset( $input['nombre_formulario_de_eventos_1'] ) ) {
			$sanitary_values['nombre_formulario_de_eventos_1'] = sanitize_text_field( $input['nombre_formulario_de_eventos_1'] );
		}

		return $sanitary_values;
	}

	public function cf7_uao_section_info() {
		
	}

	public function nombre_formulario_de_programas_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="cf7_uao_option_name[nombre_formulario_de_programas_0]" id="nombre_formulario_de_programas_0" value="%s">',
			isset( $this->cf7_uao_options['nombre_formulario_de_programas_0'] ) ? esc_attr( $this->cf7_uao_options['nombre_formulario_de_programas_0']) : ''
		);
	}

	public function nombre_formulario_de_eventos_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="cf7_uao_option_name[nombre_formulario_de_eventos_1]" id="nombre_formulario_de_eventos_1" value="%s">',
			isset( $this->cf7_uao_options['nombre_formulario_de_eventos_1'] ) ? esc_attr( $this->cf7_uao_options['nombre_formulario_de_eventos_1']) : ''
		);
	}

}
if ( is_admin() )
	$cf7_uao = new CfUAO();

/* 
 * Retrieve this value with:
 * $cf7_uao_options = get_option( 'cf7_uao_option_name' ); // Array of All Options
 * $nombre_formulario_de_programas_0 = $cf7_uao_options['nombre_formulario_de_programas_0']; // Nombre formulario de programas
 * $nombre_formulario_de_eventos_1 = $cf7_uao_options['nombre_formulario_de_eventos_1']; // Nombre formulario de eventos
 */
$cf7_uao_options = get_option( 'cf7_uao_option_name' );

$nombre_formulario_de_programas_0 = $cf7_uao_options['nombre_formulario_de_programas_0']; // Nombre formulario de programas

$nombre_formulario_de_eventos_1 = $cf7_uao_options['nombre_formulario_de_eventos_1']; // Nombre formulario de eventos